spring:
  application:
    name: service-registry
server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    fetch-registry: false
    register-with-eureka: false
